// Generated by scripts/marketing-content-release.ts. Do not edit.
// prettier-ignore
export const marketingPageKeys = [
  'tool:ai-image-generator:en',
  'tool:ai-image-generator:zh',
] as const;
// prettier-ignore
export const marketingDirectoryKeys = [
  'tools:en',
  'tools:zh',
] as const;
// prettier-ignore
export const marketingHomeProjectionLocales = [
  'en',
  'zh',
] as const;
