// Generated by scripts/marketing-content-release.ts. Do not edit.
// prettier-ignore
export const marketingPageKeys = [] as const;
// prettier-ignore
export const marketingDirectoryKeys = [] as const;
// prettier-ignore
export const marketingHomeProjectionLocales = [] as const;
