// Generated by scripts/marketing-content-release.ts. Do not edit.
// prettier-ignore
export const marketingPageKeys = [
  'model:seedance-2-5:en',
  'model:seedance-2-5:zh',
  'tool:ai-image-generator:en',
  'tool:ai-image-generator:zh',
] as const;
// prettier-ignore
export const marketingDirectoryKeys = [
  'models:en',
  'models:zh',
  'tools:en',
  'tools:zh',
] as const;
// prettier-ignore
export const marketingHomeProjectionLocales = [
  'en',
  'zh',
] as const;
